ecommerce/src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?float $Price = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $Categorie = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): static
    {
        $this->Price = $Price;

        return $this;
    }

    public function getCategorie(): ?Categories
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categories $Categorie): static
    {
        $this->Categorie = $Categorie;

        return $this;
    }
}

ecommerce/src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Products;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;
class ProductController extends AbstractController
{
    
    #[Route('/', name: 'app_product', methods: ['GET'])]
    public function list(EntityManagerInterface $entityManager): Response
    {
        // if(!$this->getUser()){
        //     return $this->redirectToRoute('app_login');
        // }
        $products = $entityManager->getRepository(Products::class)->findAll();
        return $this->render('product/list.html.twig', ['products' => $products]);
    }

    #[Route('/product/{id}', name: 'app_product_detail', methods: ['GET'])]
    public function detail(int $id, EntityManagerInterface $entityManager): Response
    {
        $product = $entityManager->getRepository(Products::class)->find($id);
        return $this->render('product/detail.html.twig', ['product' => $product]);
    }
}

ecommerce/templates/product/detail.html.twig
<h1>{{ product.name }}</h1>
<p>{{ product.description }}</p>
<p>Price: ${{ product.price }}</p>
<form action="{{ path('cart_add', {'id': product.id}) }}" method="POST">
    <label for="quantity">Quantity:</label>
    <input type="number" id="quantity" name="quantity" value="1" min="1">
    <button type="submit">Add to Cart</button>
</form>

ecommerce/templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>D:/WORK/Entretient/ecommerce/src/Controller/ProductController.php</code></li>
        <li>Your template at <code>D:/WORK/Entretient/ecommerce/templates/product/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

ecommerce/templates/product/list.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <h1>{{ 'Product List'|trans }}</h1>
    <ul>
        {% for product in products %}
            <li>
                <a href="{{ path('app_product_detail', {'id': product.id}) }}">{{ product.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}